---
title: "Article 1 : Coronavirus: Study finds further door opener into the cell"
description: |
 This article is about the Coronavirus and how it gets inside the cell.
author:
  - name: Claudia Vastola
    url: {}
date: 10-26-2020
preview : Coronavirus1
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Article 1: Coronavirus: Study finds further door opener into the cell


## I – Source of the article with publication date and word count:


Source of the article:  <https://www.sciencedaily.com/releases/2020/10/201020105526.htm> 
(20/10/2020)


Word count: 783


## II – Vocabulary: 


| Word from the text | Synonym/definition in English | French translation | 
|:----------:|:-------------:|:------:|
| SARS-CoV-2 | Severe acute respiratory syndrome coronavirus 2 | SARS-CoV-2 |
| ACE2 | Angiotensin-converting enzyme 2 | ACE2 |
| Neuropilin -1 | protein that in humans is encoded by the NRP1 gene | Neuropilin-1 |
| outbreak | a sudden occurrence or appearance | Déclenchement/poussée |
| Viral shedding | expulsion and release of virus progeny following successful reproduction during a host-cell infection | excrétion virale |
| tropism | indicating a tendency to turn or develop in response to a certain stimulus | tropisme |
| Docking sites | The substrate specificities of protein kinases have been found, in many cases, to be determined at least in part by short regions within the substrate | sites d'amarrages |
| furin | Enzyme that in humans is encoded by the FURIN gene | furine |
| Thus | in the way just indicated | Par conséquent |


## III – Analysis table about the study:


| Researchers? | DZNE German Center for Neurodegenerative Diseases
Mikael Simons together with Giuseppe Balistreri's group at the University of Helsinki.|
|:----------:|:-------------:|
| Published in? when (if mentioned)? |Journal Science | 
| General topic | The coronavirus SARS-CoV-2 and how he enters the cell. |
|Procedure/what was examined | 1. Availability of docking sites 2. Spike proteins    * Insertion of a furin cleavage site    * Amino acid sequence    * Bind to neuropilins at the cell surface 3. Cells cultured in the laboratory     * Artificial viruses that mimick SARS-CoV-2 + Naturally occurring virus   * Blocking neuripilin-1 with antibodies 4. Tissue samples from deceased patients 5. Mice   * Nanoparticles of the virus administered to the nose |
| Conclusions/discovery | Coronavirus SARS-CoV-2:   * infect cells via the receptor ACE2.   * Facilitated entrance with neuropilin-1 |
|Remaining questions | A starting point for future therapies? | 


