---
title: "Introduction"
description: |
 
author:
  - name: Claudia Vastola
    url: {}
date: 10-10-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

  Corona virus (Covid-19/SARS-CoV-2) is a contagious disease caused by severe acute respiratory syndrome. 
The first case was identified in Wuhan, China, in December 2019.
Not long after that the virus has spread worldwide becoming a global pandemic. 


  Governments decided to close borders and suspend all non-vital services and activities; they also put the population in lockdown for several months. In most countries, citizens are required to use a protective mask every time they would exit their home. In Belgium the first lockdown started on March 13th, 2020 and lasted until the beginning of May.


  Some of the symptoms are very common like fever, cough, fatigue and therefore, sometimes mistaken for a normal cold. Other symptoms, that present themselves only if one catches the virus, are loss of smell and taste and breathing difficulties. In the worst cases it can result in the death of the patient.
  Symptoms may begin one to fourteen days after exposure to the virus. Some people are symptomatic, and some are asymptomatic which means that one can catch the virus without feeling any of the symptoms.


  Since the start of the pandemic, the multinational pharmaceutical industry and the governments are collaborating to develop a cure. They created different vaccines against COVID-19. Governments started the vaccination at the beginning of 2021.
  During the pandemic some new SARS-CoV-2 variants are circulating and it’s not a certainty that the vaccines can be effective on them.
    
    
  Every day we learn something new about the virus and the cure, but it is still a long way until the end of the pandemic, the beginning of a new “normal” life and society.

