---
title: "Article 7: Covid blood protein offers clues for treatments "
description: |
 This article talks about an inflammatory protein found higher in the blood of dead patients.
author:
  - name: Claudia Vastola
    url: {}
date: 03-15-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Article 7 : Covid blood protein offers clues for treatments  


## I – Source of the article with publication date and word count:


Source of the article:  <https://www.bbc.com/news/health-56352128> (11/03/2021)


Word count: 379


## II – Vocabulary: 


| Word from the text | Synonym/definition in English | French translation | 
|:----------:|:-------------:|:------:|
| **Covid-19** | Illness caused by SARS-CoV-2 virus | covid-19|
| **Dampening** | make slightly wet | humecter |
| **Drugs** | Medicine | médicament |
| **GM-CFS** | Protein | GM-CFS proteine|
| **Harm** | Damage | abimer |
| **Immunology** | Science of the immune system | immunologie |
| **Immunosuppressive** | Drug to weaken immune system | immuosuppressive |
| **Lungs** | Organ | poumons |
| **Pinpoint** | Show exact cause | identifier |
| **Steroids** | Steroid drug | stéroide |
| **Swine flu** | H1N1 strain of influenza | grippe porcine |
| **Therapy** | Treatment | thérapie |
| **Trialled** | Experimental attempt | essai |
| **Virus** | Infectious life form | virus |
| **Whether** | Regardless of which | que |


## III – Analysis table about the study:


**Researchers?** 


    * UK scientists 
    * Dr Kenneth Baillie, at the University of Edinburgh 
    * Professor Peter Openshaw, of Imperial College London,



**Published in? when (if mentioned)?**  


(Science Immunology)


**General topic**  


The protein GM-CSF  was found to be nearly 10 times higher in patients who died from the virus.


**Procedure/what was examined** 


    * They analysed the blood samples from 470 patients admitted to hospital with Covid-19 in the UK, 
    * They compared them with samples from people with mild coronavirus, healthy people and stored samples from people who had previously had swine flu.
    * Patients with severe Covid-19 we're building a clearer picture of lung disease in Covid-19. 
    * Lungs are being damaged by the patient's own immune system rather than directly being damaged by the virus



**Conclusions/discovery**   

 
    * A key inflammatory protein that rises in the blood of patients with severe Covid-19.
    * Several drugs that target GM-CSF are being trialled but none have yet been approved for use.

 
 
**Remaining questions**   ///
